services:
  - type: web
    name: gprint-web
    env: static
    staticPublishPath: ./build
    buildCommand: bun install && bun run build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
