services:
  - type: web
    name: gprint-web
    runtime: static
    buildCommand: bun install && bun run build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /index.html
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
